Repository WilliamLwj/PyXAB, pull requests merged in 2023-03, with the labels that each got.

#23 new HOO implementation with doc, changed StoSOO testing #22 #19
  PyXAB/algos/HOO.py
  PyXAB/algos/StoSOO.py
  PyXAB/run_synthetic.py
  PyXAB/tests/test_algos/test_HOO.py
  PyXAB/tests/test_algos/test_StoSOO.py
  docs/source/api/algorithms.rst
Labels: documentation, enhancement

#26 Documentations and Tests for SequOOL and StroquOOL; new SOO algorithm that is able to use small h_max
  PyXAB/algos/SOO.py
  PyXAB/algos/SequOOL.py
  PyXAB/algos/StroquOOL.py
  PyXAB/tests/test_algos/test_SOO.py
  PyXAB/tests/test_algos/test_SequOOL.py
  PyXAB/tests/test_algos/test_StroquOOL.py
Labels: enhancement

#29 Fixed the bugs #27
  PyXAB/algos/GPO.py
  PyXAB/algos/PCT.py
  PyXAB/algos/POO.py
  PyXAB/algos/VPCT.py
  PyXAB/tests/test_algos/test_GPO.py
  PyXAB/tests/test_algos/test_PCT.py
  PyXAB/tests/test_algos/test_POO.py
  PyXAB/tests/test_algos/test_VPCT.py
  PyXAB/utils/run_cumulative.py
Labels: bug, enhancement
